## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999

matrix:
  include:
  - name: "running examples"
  - script:
    - julia -e 'include("test/setup.jl"); setup()' $TRAVIS_EVENT_TYPE
    - julia -e 'using Pkg; Pkg.build("cron_test")'
    - julia -e '@show "CUSTOM SCRIPT"; @show ARGS; include("test/runtests.jl")' $TRAVIS_EVENT_TYPE
    - julia -e 'include("test/setup.jl"); setdown()' $TRAVIS_EVENT_TYPE
